package com.guonl.dao;

import com.guonl.po.SysMenuAuthority;
import com.guonl.po.SysMenuAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuAuthorityMapper {
    long countByExample(SysMenuAuthorityExample example);

    int deleteByExample(SysMenuAuthorityExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SysMenuAuthority record);

    int insertSelective(SysMenuAuthority record);

    List<SysMenuAuthority> selectByExample(SysMenuAuthorityExample example);

    SysMenuAuthority selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SysMenuAuthority record, @Param("example") SysMenuAuthorityExample example);

    int updateByExample(@Param("record") SysMenuAuthority record, @Param("example") SysMenuAuthorityExample example);

    int updateByPrimaryKeySelective(SysMenuAuthority record);

    int updateByPrimaryKey(SysMenuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_authority
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysMenuAuthority selectOneByExample(SysMenuAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_authority
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SysMenuAuthority> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu_authority
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SysMenuAuthority> list, @Param("selective") SysMenuAuthority.Column ... selective);
}